name: nipaplay
description: "咪啪～☆."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.7.10

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Shelf for web server
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  window_manager: ^0.4.3
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  file_selector: ^1.0.3
  path_provider: ^2.1.2
  path: ^1.9.1
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  glassmorphism: ^3.0.0
  fvp: ^0.33.1
  http: ^1.3.0
  xml: ^6.5.0
  crypto: ^3.0.3
  cached_network_image: ^3.4.1
  file_picker: ^8.0.6
  hugeicons: ^0.0.10
  url_launcher: ^6.3.1
  universal_html: ^2.2.4
  kmbal_ionicons: ^1.0.0
  image: ^4.5.4
  intl: ^0.20.2
  uuid: ^4.5.1
  transparent_image: ^2.0.1
  wakelock_plus: ^1.3.2
  screen_brightness: ^2.1.3
  volume_controller: ^3.4.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3  # 用于桌面平台
  video_player: 2.9.5
  media_kit:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  qr_flutter: ^4.1.0  # 用于生成二维码
  flutter_svg: ^2.0.14  # 用于显示SVG图标
  desktop_drop: ^0.6.1
  cupertino_icons: ^1.0.8
  charset_converter: ^2.1.1
  system_info2: ^3.0.1
  hotkey_manager: ^0.2.3
  fluent_ui: ^4.12.0
  adaptive_platform_ui: ^0.1.98

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "icons/new-icon-win.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "icons/new-icon-win.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "icons/new-icon-mac.png"
  linux:
    generate: true
    image_path: "icons/new-icon-win.png"

  # Android 使用 new-icon.png
  image_path: "icons/new-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icons/new-icon.png"

  # iOS 使用 new-icon-apple.png
  image_path_ios: "icons/new-icon-apple.png"
  image_path_ios_dark_transparent:  "icons/new-icon-apple-dark.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/logo.png
    - assets/images/logo512.png
    - assets/backempty.png
    - assets/nipaplay.png
    - assets/dandanplay.png
    - assets/bangumi.png
    - assets/images/main_image.png
    - assets/images/main_image_mobile.png
    - assets/subfont.ttf
    - assets/jellyfin.svg
    - assets/emby.svg
    - assets/images/
    - others/赞赏码.jpg
    - assets/shaders/anime4k/
    # --- Web UI Assets ---
    - assets/web/
    - assets/web/assets/
    - assets/web/assets/assets/
    - assets/web/assets/assets/images/
    - assets/web/assets/fonts/
    - assets/web/assets/packages/
    - assets/web/assets/packages/cupertino_icons/
    - assets/web/assets/packages/cupertino_icons/assets/
    - assets/web/assets/packages/hugeicons/
    - assets/web/assets/packages/hugeicons/lib/
    - assets/web/assets/packages/hugeicons/lib/fonts/
    - assets/web/assets/packages/kmbal_ionicons/
    - assets/web/assets/packages/kmbal_ionicons/assets/
    - assets/web/assets/packages/kmbal_ionicons/assets/fonts/
    - assets/web/assets/packages/media_kit/
    - assets/web/assets/packages/media_kit/assets/
    - assets/web/assets/packages/media_kit/assets/web/
    - assets/web/assets/packages/wakelock_plus/
    - assets/web/assets/packages/wakelock_plus/assets/
    - assets/web/assets/shaders/
    - assets/web/canvaskit/
    - assets/web/canvaskit/chromium/
    - assets/web/icons/
    # ---------------------
    
  # GPU着色器文件
    
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: subfont
      fonts:
        - asset: assets/subfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Add dependency_overrides for all media_kit related packages
dependency_overrides:
  # Fix fluent_ui ShuntingYardParser compatibility issue
  math_expressions: 2.3.1
  fluent_ui: 4.11.0
  media_kit:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Shinokawa/media-kit.git
      ref: main
      path: ./libs/macos/media_kit_libs_macos_video
